# Generated by Django 4.0.3 on 2022-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Location',
            field=models.CharField(default='Ruislip', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
